allowBuilds:
  "@xai-official/grok": false
  better-sqlite3-multiple-ciphers: true
  electron: true
  electron-winstaller: false
  esbuild: true
  lzma-native: false
  node-pty: true
  opencode-ai: false
storeDir: .cache/pnpm
