import { z } from "zod";

export const runtimeDriverSchema = z.enum([
  "native_cli",
  "app_server",
  "acp",
  "api",
]);

export const runtimeAuthenticationSchema = z.enum([
  "external_cli",
  "browser_subscription",
  "provider_managed",
  "api_key",
]);

export const runtimeCapabilitySchema = z.enum([
  "sessions",
  "streaming",
  "tools",
  "approvals",
  "models",
  "usage",
  "context",
  "subagents",
]);

export const runtimeManifestSchema = z.object({
  schemaVersion: z.literal(1),
  runtimeId: z.string().min(1),
  displayName: z.string().min(1),
  providerId: z.string().min(1),
  driver: runtimeDriverSchema,
  authentication: runtimeAuthenticationSchema,
  accountStrategy: z.string().min(1),
  executable: z.string().min(1).nullable(),
  protocolVersion: z.string().min(1),
  capabilities: z.array(runtimeCapabilitySchema),
});

export type RuntimeManifest = z.infer<typeof runtimeManifestSchema>;

export const builtInRuntimeManifests = {
  claude: {
    schemaVersion: 1,
    runtimeId: "claude",
    displayName: "Claude",
    providerId: "anthropic",
    driver: "native_cli",
    authentication: "external_cli",
    accountStrategy: "claude_cli",
    executable: "claude",
    protocolVersion: "stream-json",
    capabilities: ["sessions", "streaming", "tools", "approvals", "usage"],
  },
  codex: {
    schemaVersion: 1,
    runtimeId: "codex",
    displayName: "Codex",
    providerId: "openai",
    driver: "app_server",
    authentication: "provider_managed",
    accountStrategy: "codex_app_server",
    executable: "codex",
    protocolVersion: "app-server-jsonl",
    capabilities: [
      "sessions",
      "streaming",
      "tools",
      "approvals",
      "usage",
      "context",
    ],
  },
  cursor: {
    schemaVersion: 1,
    runtimeId: "cursor",
    displayName: "Cursor",
    providerId: "cursor",
    driver: "native_cli",
    authentication: "browser_subscription",
    accountStrategy: "cursor_subscription",
    executable: "cursor-agent",
    protocolVersion: "stream-json",
    capabilities: ["sessions", "streaming", "tools", "models", "usage"],
  },
  agy: {
    schemaVersion: 1,
    runtimeId: "agy",
    displayName: "Antigravity",
    providerId: "google-antigravity",
    driver: "native_cli",
    authentication: "browser_subscription",
    accountStrategy: "agy_subscription",
    executable: "agy",
    protocolVersion: "companion-hook",
    capabilities: ["sessions", "streaming", "tools", "approvals", "usage"],
  },
  grok: {
    schemaVersion: 1,
    runtimeId: "grok",
    displayName: "Grok",
    providerId: "xai",
    driver: "native_cli",
    authentication: "browser_subscription",
    accountStrategy: "grok_subscription",
    executable: "grok",
    protocolVersion: "stream-json",
    capabilities: ["sessions", "streaming", "tools", "usage"],
  },
  mimo: {
    schemaVersion: 1,
    runtimeId: "mimo",
    displayName: "MiMo",
    providerId: "xiaomi",
    driver: "native_cli",
    authentication: "api_key",
    accountStrategy: "environment_api_key",
    executable: "mimo",
    protocolVersion: "stream-json",
    capabilities: ["sessions", "streaming", "tools", "usage"],
  },
  minimax: {
    schemaVersion: 1,
    runtimeId: "minimax",
    displayName: "MiniMax",
    providerId: "minimax",
    driver: "native_cli",
    authentication: "api_key",
    accountStrategy: "environment_api_key",
    executable: "mmx",
    protocolVersion: "json",
    capabilities: ["sessions", "streaming", "usage"],
  },
  opencode: {
    schemaVersion: 1,
    runtimeId: "opencode",
    displayName: "OpenCode",
    providerId: "multi-provider",
    driver: "acp",
    authentication: "provider_managed",
    accountStrategy: "provider_selected",
    executable: "opencode",
    protocolVersion: "acp-0.21",
    capabilities: [
      "sessions",
      "streaming",
      "tools",
      "approvals",
      "models",
      "context",
    ],
  },
} as const satisfies Record<string, RuntimeManifest>;
