// Channel names only — no zod, no runtime dependencies. The sandboxed preload
// imports this module and must stay dependency-free.
export const ipcChannels = [
  "system:doctor",
  "models:list",
  "task:create",
  "task:rename",
  "task:delete",
  "workspace:pick",
  "file:pick",
  "fs:list",
  "fs:read",
  "fs:search",
  "terminal:open",
  "terminal:write",
  "terminal:resize",
  "terminal:close",
  "run:list",
  "run:events",
  "lane:setPermissionMode",
  "task:archive",
  "task:fork",
  "conversation:export",
  "audit:export",
  "eco:mcp",
  "eco:skills",
  "eco:memoryList",
  "eco:memoryRead",
  "eco:memoryWrite",
  "eco:settings",
  "eco:agents",
  "task:list",
  "kanban:list",
  "kanban:create",
  "kanban:move",
  "kanban:assign",
  "lane:list",
  "conversation:history",
  "lane:ensure",
  "lane:open",
  "lane:sendTurn",
  "run:cancel",
  "approval:resolve",
  "quickChat:create",
  "quickChat:send",
  "usage:overview",
  "usage:refresh",
  "usage:alertSet",
  "memory:configure",
  "memory:list",
  "memory:search",
  "memory:reindex",
  "calendar:sources:list",
  "calendar:source:createLocal",
  "calendar:source:createLinked",
  "calendar:events:list",
  "calendar:event:createLocal",
  "calendar:event:updateLocal",
  "calendar:event:deleteLocal",
  "inbox:accounts:list",
  "inbox:account:add",
  "inbox:account:remove",
  "inbox:account:sync",
  "inbox:account:updateCredential",
  "inbox:account:connectGoogle",
  "inbox:account:reauthorizeGoogle",
  "inbox:account:outgoing:get",
  "inbox:account:outgoing:set",
  "inbox:threads:list",
  "inbox:thread:get",
  "inbox:thread:markRead",
  "inbox:thread:markUnread",
  "inbox:thread:moveToSpam",
  "inbox:thread:moveToTrash",
  "inbox:thread:createTask",
  "inbox:thread:createReplyDraft",
  "inbox:thread:createForwardDraft",
  "inbox:thread:generateReplyDraft",
  "inbox:thread:replyActions:list",
  "inbox:reply:discard",
  "inbox:reply:approveAndSend",
] as const;

export type IpcChannel = (typeof ipcChannels)[number];

export const eventChannel = "workbench:event";

export const terminalDataChannel = "terminal:data";
